on:
  pull_request:
  push:
jobs:
  ubuntu-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Go modules
      run: go mod download
    - name: Install tools
      run: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
        cd $(mktemp -d)
        go mod init tmp
        go get github.com/rakyll/statik
        go get mvdan.cc/gofumpt/gofumports
    - name: Generate
      run: |
        PATH=$PATH:$(go env GOPATH)/bin go generate ./...
        git diff --exit-code
    - name: Build
      run: go build ./...
    - name: Run
      run: go run . --version
    - name: Test
      run: go test -race ./...
    - name: Lint
      run: $(go env GOPATH)/bin/golangci-lint run
    - name: Check formatting
      run: |
        find . -name \*.go | xargs $(go env GOPATH)/bin/gofumports -w
        git diff --exit-code
    - name: Check completions
      run: |
        go run . completion bash > completions/chezmoi-completion.bash
        go run . completion fish > completions/chezmoi.fish
        go run . completion zsh > completions/chezmoi.zsh
        git diff --exit-code
  macos-ci:
    runs-on: macos-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Go modules
      run: go mod download
    - name: Build
      run: go build ./...
    - name: Run
      run: go run . --version
    - name: Test
      run: go test -race ./...
  windows-ci:
    runs-on: windows-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Go modules
      run: go mod download
    - name: Build
      run: go build ./...
    - name: Run
      run: go run . --version
    - name: Test
      run: go test -race ./...
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
    - ubuntu-ci
    - macos-ci
    - windows-ci
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Go modules
      run: go mod download
    - name: Install tools
      run: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- v1.21.0
        go get github.com/gobuffalo/packr/v2/packr2
    - name: Generate
      run: |
        PATH=$PATH:$(go env GOPATH)/bin go generate ./...
        go run . completion bash > completions/chezmoi-completion.bash
        go run . completion fish > completions/chezmoi.fish
        go run . completion zsh > completions/chezmoi.zsh
        git diff --exit-code
    - name: Set up Snapcraft
      env:
        SNAPCRAFT_LOGIN: ${{ secrets.SNAPCRAFT_LOGIN }}
      run: |
        sudo snap install snapcraft --classic
        sudo chown root:root /
        echo ${SNAPCRAFT_LOGIN} | snapcraft login --with -
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      run: |
        sudo snap install goreleaser --classic
        goreleaser release